Autogenerated tree updates.
merged:

  flora: 523a446b976b43c4ede7fd49048643aaf4812e42
  gentoo-staging: 9292583023a6610905c79a4707db3ac6c63b3a31
  kit-fixups: 04b7b943846afb83ce325ebdf993ebbac5ecbdb2

diff --git a/dev-libs/klibc/templates/klibc.tmpl b/dev-libs/klibc/templates/klibc.tmpl
--- a/dev-libs/klibc/templates/klibc.tmpl
+++ b/dev-libs/klibc/templates/klibc.tmpl
@@ -1,6 +1,4 @@
-# Copyright 1999-2017 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
-
 # Robin H. Johnson <robbat2@gentoo.org>, 12 Nov 2007:
 # This still needs major work.
 # But it is significently better than the previous version.
@@ -12,52 +10,24 @@
 # Because they have to be configured in a way that differs from the copy in
 # /usr/src/. The sys-kernel/linux-headers are too stripped down to use
 # unfortunately.
-# This will be able to go away once the klibc author updates his code
-# to build again the headers provided by the kernel's 'headers_install' target.
 
-EAPI=6
-K_TARBALL_SUFFIX="xz"
+EAPI=7
 
 inherit eutils toolchain-funcs flag-o-matic
 
 DESCRIPTION="A minimal libc subset for use with initramfs"
 HOMEPAGE="http://www.zytor.com/mailman/listinfo/klibc/ https://www.kernel.org/pub/linux/libs/klibc/"
-KV_MAJOR="4" KV_MINOR="x" KV_SUB="4"
-PKV_EXTRA=""
-if [[ ${PKV_EXTRA} ]]; then
-	if [[ ${KV_MAJOR} == 2 ]]; then
-		PKV="${KV_MAJOR}.${KV_MINOR}.$((${KV_SUB}+1))-${PKV_EXTRA}"
-	else
-		PKV="${KV_MAJOR}.$((${KV_SUB}+1))-${PKV_EXTRA}"
-	fi
-	PATCH_URI="mirror://kernel/linux/kernel/v${KV_MAJOR}.${KV_MINOR}/patch-${PKV}.${K_TARBALL_SUFFIX}"
-fi
-if [[ ${KV_MAJOR} == 2 ]]; then
-	OKV="${KV_MAJOR}.${KV_MINOR}.${KV_SUB}"
-else
-	OKV="${KV_MAJOR}.${KV_SUB}"
-fi
-KERNEL_URI="
-	mirror://kernel/linux/kernel/v${KV_MAJOR}.${KV_MINOR}/linux-${OKV}.tar.${K_TARBALL_SUFFIX}
-	mirror://kernel/linux/kernel/v${KV_MAJOR}.${KV_MINOR}/testing/linux-${OKV}.tar.${K_TARBALL_SUFFIX}"
-DEBIAN_PV=2.0.4
-DEBIAN_PR=9
-DEBIAN_A="${PN}_${DEBIAN_PV}-${DEBIAN_PR}.debian.tar.xz"
-SRC_URI="
-	mirror://kernel/linux/libs/klibc/${PV:0:3}/${P}.tar.${K_TARBALL_SUFFIX}
-	mirror://debian/pool/main/k/klibc/${DEBIAN_A}
-	${PATCH_URI}
-	${KERNEL_URI}"
+SRC_URI="{{artifacts|map(attribute='src_uri')|join(' ')}}"
 
 LICENSE="|| ( GPL-2 LGPL-2 )"
-KEYWORDS="~alpha amd64 ~arm ia64 -mips ~ppc ~ppc64 ~sparc x86"
+KEYWORDS="*"
 SLOT="0"
 IUSE="debug test custom-cflags"
 
 DEPEND="dev-lang/perl"
 RDEPEND="${DEPEND}"
 
-KS="${WORKDIR}/linux-${OKV}"
+KS="${WORKDIR}/linux-{{".".join(headers_version)}}"
 
 # Klibc has no PT_GNU_STACK support, so scanning for execstacks is moot
 QA_EXECSTACK="*"
@@ -77,7 +47,7 @@ kernel_asm_arch() {
 	esac
 }
 
-# For a given Gentoo ARCH,
+# For a given ARCH,
 # specify the kernel defconfig most relevant
 kernel_defconfig() {
 	a="${1:${ARCH}}"
@@ -90,33 +60,17 @@ kernel_defconfig() {
 	esac
 }
 
-src_unpack() {
-	unpack linux-${OKV}.tar.${K_TARBALL_SUFFIX} ${P}.tar.${K_TARBALL_SUFFIX} ${DEBIAN_A}
-}
-
 PATCHES=(
 	# Build interp.o with EXTRA_KLIBCAFLAGS (.S source)
 	"${FILESDIR}"/${PN}-1.4.11-interp-flags.patch
-	# Fix usage of -s, bug #201006
-	"${FILESDIR}"/klibc-1.5.7-strip-fix-dash-s.patch
 	# The inline definition from sys/stat.h does not seem to get used
 	# So just copy it to make this compile for now
 	"${FILESDIR}"/klibc-2.0.2-mkfifo.patch
-	# Newer kernels have some headers in the uapi dir
-	"${FILESDIR}"/klibc-2.0.3-kernel-uapi.patch
 )
 
 src_prepare() {
-	[[ ${PKV} ]] && eapply "${DISTDIR}"/patch-${PKV}.${K_TARBALL_SUFFIX}
-
-	# Symlink /usr/src/linux to ${S}/linux
-	ln -snf "${KS}" linux
-	#ln -snf "/usr" linux
-
-	# Borrow the debian fixes too
-	for p in $(<"${WORKDIR}"/debian/patches/series) ; do
-		PATCHES+=( "${WORKDIR}/debian/patches/${p}" )
-	done
+	# Symlink /usr to ${S}/linux
+	ln -snf "${KS}/usr" linux
 
 	default
 }
@@ -168,7 +122,7 @@ src_compile() {
 		"${KS}"/.config \
 		"${S}"/defconfig
 	fi
-	emake prepare CC="${CC}" HOSTCC="${HOSTCC}" ARCH="${KLIBCASMARCH}" || die "Failed to prepare kernel sources for header usage"
+	emake headers_install CC="${CC}" HOSTCC="${HOSTCC}" ARCH="${KLIBCASMARCH}" || die "Failed to install kernel headers"
 
 	cd "${S}"
 
@@ -184,19 +138,17 @@ src_compile() {
 		KLIBCOPTFLAGS='-nostdlib' \
 		HOSTCC="${HOSTCC}" CC="${CC}" \
 		HOSTLD="${HOSTLD}" LD="${LD}" \
-		INSTALLDIR="/usr/${libdir}/klibc" \
+		INSTALLDIR="/usr/$(get_libdir)/klibc" \
 		KLIBCARCH=${KLIBCARCH} \
 		KLIBCASMARCH=${KLIBCASMARCH} \
-		SHLIBDIR="/${libdir}" \
-		libdir="/usr/${libdir}" \
+		SHLIBDIR="/$(get_libdir)" \
+		libdir="/usr/$(get_libdir)" \
 		mandir="/usr/share/man" \
 		T="${T}" \
 		$(use custom-cflags || echo SKIP_)HOSTCFLAGS="${CFLAGS}" \
 		$(use custom-cflags || echo SKIP_)HOSTLDFLAGS="${LDFLAGS}" \
 		$(use custom-cflags || echo SKIP_)KLIBCOPTFLAGS="${CFLAGS}" \
 		${myargs} || die "Compile failed!"
-
-		#SHLIBDIR="/${libdir}" \
 
 	ARCH="${myARCH}" ABI="${myABI}"
 }
@@ -234,12 +186,12 @@ src_install() {
 		KLIBCOPTFLAGS='-nostdlib' \
 		HOSTCC="${HOSTCC}" CC="${CC}" \
 		HOSTLD="${HOSTLD}" LD="${LD}" \
-		INSTALLDIR="/usr/${libdir}/klibc" \
+		INSTALLDIR="/usr/$(get_libdir)/klibc" \
 		INSTALLROOT="${D}" \
 		KLIBCARCH=${KLIBCARCH} \
 		KLIBCASMARCH=${KLIBCASMARCH} \
-		SHLIBDIR="/${libdir}" \
-		libdir="/usr/${libdir}" \
+		SHLIBDIR="/$(get_libdir)" \
+		libdir="/usr/$(get_libdir)" \
 		mandir="/usr/share/man" \
 		T="${T}" \
 		$(use custom-cflags || echo SKIP_)HOSTCFLAGS="${CFLAGS}" \
@@ -248,22 +200,20 @@ src_install() {
 		${myargs} \
 		install || die "Install failed!"
 
-		#SHLIBDIR="/${libdir}" \
-
 	# klibc doesn't support prelinking, so we need to mask it
 	cat > "${T}/70klibc" <<-EOF
-		PRELINK_PATH_MASK="/usr/${libdir}/klibc"
+		PRELINK_PATH_MASK="/usr/$(get_libdir)/klibc"
 	EOF
 
 	doenvd "${T}"/70klibc
 
-	# Fix the permissions (bug #178053) on /usr/${libdir}/klibc/include
+	# Fix the permissions (bug #178053) on /usr/$(get_libdir)/klibc/include
 	# Actually I have no idea, why the includes have those weird-ass permissions
 	# on a particular system, might be due to inherited permissions from parent
 	# directory
 	# NOTE: This totally violates sandbox <asturm@gentoo.org>
-	# find "${D}"/usr/${libdir}/klibc/include | xargs chmod o+rX
-	find "${D}"/usr/${libdir}/klibc/include -type f \
+	# find "${D}"/usr/$(get_libdir)/klibc/include | xargs chmod o+rX
+	find "${D}"/usr/$(get_libdir)/klibc/include -type f \
 		\( -name '.install' -o -name '..install.cmd' \) -delete || die
 
 	# Hardlinks becoming copies
@@ -285,7 +235,7 @@ src_install() {
 
 	# Fix up the symlink
 	# Mainly for merged arches
-	linkname="${D}/usr/${libdir}/klibc/include/asm"
+	linkname="${D}/usr/$(get_libdir)/klibc/include/asm"
 	if [ -L "${linkname}" ] && [ ! -e "${linkname}" ] ; then
 		ln -snf asm-${KLIBCASMARCH} "${linkname}"
 	fi
