updates
merged:

  flora: 3978b643c73d950701a69241a596509e8b08679d
  faustoo: 6cffe50450347b723e4944934bf810b80fd072f8
  fusion809: d1404b6a8f3953f6b657c2ce4a3a864519a93ea7
  deadbeef: 53e0a41db6e7193bd83ef117f8055457f0990cb7
  gentoo-staging: 9292583023a6610905c79a4707db3ac6c63b3a31
  kit-fixups: 93b32498e5a7952cc6a081df8e20661585b03457

diff --git a/app-emulation/lxd/files/4.0.1/lxd.initd b/app-emulation/lxd/files/4.0.1/lxd.initd
--- a/app-emulation/lxd/files/4.0.1/lxd.initd
+++ b/app-emulation/lxd/files/4.0.1/lxd.initd
@@ -1,22 +1,24 @@
 #!/sbin/openrc-run
-# Copyright 2004-2018 Gentoo Foundation, Copryight 2018 Funtoo Solutions
 # Distributed under the terms of the GNU General Public License v2
 
-DAEMON=/usr/libexec/lxd
+DAEMON=/usr/sbin/lxd
 PIDFILE=/run/lxd.pid
+TIMEOUT=10
 
 extra_commands="stopall"
 
 depend() {
 	need net
-	use lxcfs
+	need lxcfs
 }
 
 start() {
-	# required for lxd in lxd:
-	modprobe -q ip6_tables
 	ebegin "Starting lxd service"
-	LD_LIBRARY_PATH=/usr/__LIBDIR__/lxd start-stop-daemon --start \
+	# required for loopback storage pools:
+	modprobe -f loop > /dev/null 2>&1
+	# fixing permissions on /var/lib/lxd and make sure it exists
+	install -d /var/lib/lxd --group lxd --owner root --mode 0775
+	start-stop-daemon --start \
 		--pidfile ${PIDFILE} \
 		--exec ${DAEMON} \
 		--background \
@@ -38,9 +40,13 @@ stop() {
 
 stopall() {
 	ebegin "Stopping lxd service and containers"
+	lxc stop --all --timeout $TIMEOUT >/dev/null 2>&1
+	if [ "$?" -ne 0 ]; then
+		lxc stop --all --force || eerror "Could not stop all containers"
+	fi
 	if "${DAEMON}" shutdown; then
-		/etc/init.d/lxd zap
 		rm -f ${PIDFILE}
-		fi
+		eend 0
+	fi
 	eend $?
 }
